name: push
on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      pushImage:
        description: 'Push Docker image'     
        required: true
        default: 'false'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ${GITHUB_REF} | grep -q refs/heads && echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/} || true
          echo ${GITHUB_REF} | grep -q refs/tags && echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV || true
      - name: Fallback tag name
        if: ${{ env.SOURCE_TAG == null }}
        run: echo "SOURCE_TAG=latest" >> $GITHUB_ENV
      - name: debug branch_name
        run: |
          echo $SOURCE_NAME
          echo $SOURCE_BRANCH
          echo $SOURCE_TAG
        env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.event.repository.name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.event.repository.name }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          context: .
          platforms: linux/amd64
          push: ${{ env.SOURCE_TAG != 'latest' || github.event.inputs.pushImage == 'true' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.SOURCE_TAG }}
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}